_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.10
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
path:
    value: data/students.json
