name: Train and Upload Model

on:
  push:
    paths:
      - 'data/**'
      - 'models/**'
      - 'src/**'
      - '3. Training_model.ipynb'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wandb jupyter

      - name: Set wandb API key
        run: |
          echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" >> $GITHUB_ENV

      - name: Run training notebook
        run: |
          jupyter nbconvert --to notebook --inplace --execute "3. Training_model.ipynb"

      - name: Upload model to wandb
        run: |
          python src/upload_model_to_wandb.py
