_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.10
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
bootstrap:
    value: false
max_depth:
    value: 5
max_features:
    value: null
min_samples_leaf:
    value: 5
min_samples_split:
    value: 5
n_estimators:
    value: 200
