name: Retraining Pipeline

on:
  push:
    branches:
      - main

jobs:
  retrain_model:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert wandb  # Add wandb installation here

      - name: Login to W&B
        run: |
          wandb login $env:WANDB_API_KEY 

      - name: Convert Jupyter Notebooks to Python scripts
        run: |
          jupyter nbconvert --to python "2. Data_segregation.ipynb"
          jupyter nbconvert --to python "3. Training_model.ipynb"
          jupyter nbconvert --to python "4. Testing.ipynb"

      - name: Run Data Segregation
        run: |
          python "2. Data_segregation.py"

      - name: Retrain Model
        run: |
          python "3. Training_model.py"

      - name: Run Testing
        run: |
          python "4. Testing.py"
