name: Run API Test Only

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-api:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies for API test
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pytest pytest-asyncio httpx python-multipart

      - name: Run only api_test.py
        run: |
          pytest api_test.py -v
        shell: pwsh
